services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro