spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html